version: "2"
services:
  db:
    container_name: mongo
    image: mongo
    command: mongod --bind_ip_all
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: certificate
    restart: always
    build: .
    ports:
      - "3000:3000"
    dns_search: ''
    links:
      - db
    environment:
      MONGODB_HOST: 'db'